const { merge } = require("webpack-merge");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const Dotenv = require("dotenv-webpack");

const base = require("./webpack.base");
const { appPath } = require("./constants");

module.exports = merge(base, {
  mode: "development",
  entry: [
    appPath, // Start with js/app.js
  ],
  devServer: {
    hot: true,
    compress: true,
    open: false,
    port: 3000,
    historyApiFallback: true, // for react router dom
  },

  output: {
    publicPath: "/",
  },

  plugins: [
    new Dotenv(),
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: "public/index.html",
      favicon: "public/favicon.ico",
      minify: {
        removeComments: true,
        collapseWhitespace: true,
      },
    }),
  ],

  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: "eval-source-map",
});
